export const WELCOME_PAGE="Welcome page";
export const HOD_SPEECH="HOD's Speech"
export const PREFACE ="Preface";
export const COLLEGE_ANTHEM = "College Anthem";
export const PRINCIPAL_OFFICERS="Principal Officers";
export const ABOUT_VISION_MISSION ="About Us, Vision & Mission";
export const  LIST_OF_LECTURERS="List of Lecturers";
export const TABLE_COURSES = "Table of Courses";
export const COURSE_DETAILS = "Course Details";
export const  DEPARTMENTAL_DETAILS="Departmental Details"
